apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/instance: smm-openart
    app.kubernetes.io/name: mariadb
    statefulset.kubernetes.io/pod-name: smm-openart-mariadb-0
  name: smm-openart-mariadb-0
  namespace: opencart
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: primary
              app.kubernetes.io/instance: smm-openart
              app.kubernetes.io/name: mariadb
          namespaces:
          - opencart
          topologyKey: kubernetes.io/hostname
        weight: 1
  initContainers:
  - name: mariadb-create-directory-structure
    image: busybox
    command:
      [
        "sh",
        "-c",
        "/bin/mkdir -p /bitnami/mariadb/data &&  /bin/chmod -R 775 /bitnami/mariadb",
      ]
    volumeMounts:
    - mountPath: /bitnami/mariadb
      name: data
  containers:
  - env:
    - name: BITNAMI_DEBUG
      value: "false"
    - name: MARIADB_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mariadb-root-password
          name: smm-openart-mariadb
    - name: MARIADB_USER
      value: bn_opencart
    - name: MARIADB_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mariadb-password
          name: smm-openart-mariadb
    - name: MARIADB_DATABASE
      value: bitnami_opencart
    image: docker.io/bitnami/mariadb:10.6.7-debian-10-r62
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/bash
        - -ec
        - |
          password_aux="${MARIADB_ROOT_PASSWORD:-}"
          if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
              password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
          fi
          mysqladmin status -uroot -p"${password_aux}"
      failureThreshold: 3
      initialDelaySeconds: 120
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: mariadb
    ports:
    - containerPort: 3306
      name: mysql
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /bin/bash
        - -ec
        - |
          password_aux="${MARIADB_ROOT_PASSWORD:-}"
          if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
              password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
          fi
          mysqladmin status -uroot -p"${password_aux}"
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext:
      runAsNonRoot: true
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /bitnami/mariadb
      name: data
    - mountPath: /opt/bitnami/mariadb/conf/my.cnf
      name: config
      subPath: my.cnf
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: smm-openart-mariadb-0
  restartPolicy: Always

  serviceAccount: smm-openart-mariadb
  serviceAccountName: smm-openart-mariadb
  subdomain: smm-openart-mariadb

  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: data-smm-openart-mariadb-0
  - configMap:
      defaultMode: 420
      name: smm-openart-mariadb
    name: config
