apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-smm-openart-mariadb-0
  namespace: opencart
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeMode: Filesystem


