apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: smm-openart-opencart-opencart
  namespace: opencart
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: standard
  volumeMode: Filesystem


