apiVersion: v1
kind: Secret
metadata:
  name: mynginx-tls
  namespace: demo
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlGdXpDQ0JLT2dBd0lCQWdJVE1RQUFBQWg1
    L3Bidlh4Wm5Md0FBQUFBQUNEQU5CZ2txaGtpRzl3MEJBUXNGDQpBREJMTVJVd0V3WUtDWkltaVpQ
    eUxHUUJHUllGYkc5allXd3hGVEFUQmdvSmtpYUprL0lzWkFFWkZnVnRhV3hoDQpZakViTUJrR0Ex
    VUVBeE1TYldsc1lXSXRWMGxPVTFaU0xVUkRMVU5CTUI0WERUSXlNRFF5TmpJek1qSTBORm9YDQpE
    VEkwTURReU5USXpNakkwTkZvd2N6RUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdUQWs1Wk1S
    SXdFQVlEDQpWUVFIRXdsU2IyTm9aWE4wWlhJeERqQU1CZ05WQkFvVEJXMXBiR0ZpTVJRd0VnWURW
    UVFMRXd0RVpYWmxiRzl3DQpiV1Z1ZERFZE1Cc0dBMVVFQXhNVWNtVm5hWE4wY25rdWJXbHNZV0l1
    Ykc5allXd3dnZ0VpTUEwR0NTcUdTSWIzDQpEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUMxZzdU
    UHJoOCtFbnhVeXF4QTRoMUVTTXp5dTJObWdaR0g2aWhQDQorZmtHM05VU1dQUkd3eFNmb1JURHFK
    cE80cGxsU2V0NVhqMXhxQXpMYnN3Z09rZlQ0dktQcitsZjBFa1p0VFpHDQpCOVZFQ0E1UzFyK1gz
    S0xWWjdlUnVMU0NFZnpUSlZHQ3lncDljSlhwenpJWC9MSEt5VThYbVVML2Z1ZmlWMzFGDQovbXdH
    QjcxRkRzdTNWb0Q1S0k1UnliUThuSHhldnlPbHlaSFI2Vk5HN2ZjeDFUeVVFSDhOd0NRWDlmcUNZ
    eHYrDQpQOVpJODNDR0VDME5mdW1JY2ttczNJZkRrbTU0cDRPK0J3by9KSkNHcjJ1YWhlUW1aZXJk
    eGxMNU41ZE44VDNlDQp5d1JMRktzTXpRUUFwYjJydk03TVcxdjFPejgzVk5SbzBlVjlEeklBdWpz
    dHVxc2JBZ01CQUFHamdnSnVNSUlDDQphakJFQmdOVkhSRUVQVEE3Z2hSeVpXZHBjM1J5ZVM1dGFX
    eGhZaTVzYjJOaGJJSVJjMjlqYTNNdWJXbHNZV0l1DQpiRzlqWVd5Q0VHUmxiVzh1Yldsc1lXSXVi
    RzlqWVd3d0hRWURWUjBPQkJZRUZOQ25RM0dYQWZoNDB5S0FpODFzDQo0RGJkdG52c01COEdBMVVk
    SXdRWU1CYUFGQlVRaHhEV0laWHhBOHVLa0Y4bnRhMktQN3BrTUlIU0JnTlZIUjhFDQpnY293Z2Nj
    d2djU2dnY0dnZ2I2R2didHNaR0Z3T2k4dkwwTk9QVzFwYkdGaUxWZEpUbE5XVWkxRVF5MURRU3hE
    DQpUajFYYVc1emRuSXRSRU1zUTA0OVEwUlFMRU5PUFZCMVlteHBZeVV5TUV0bGVTVXlNRk5sY25a
    cFkyVnpMRU5PDQpQVk5sY25acFkyVnpMRU5PUFVOdmJtWnBaM1Z5WVhScGIyNHNSRU05Yldsc1lX
    SXNSRU05Ykc5allXdy9ZMlZ5DQpkR2xtYVdOaGRHVlNaWFp2WTJGMGFXOXVUR2x6ZEQ5aVlYTmxQ
    MjlpYW1WamRFTnNZWE56UFdOU1RFUnBjM1J5DQphV0oxZEdsdmJsQnZhVzUwTUlIRUJnZ3JCZ0VG
    QlFjQkFRU0J0ekNCdERDQnNRWUlLd1lCQlFVSE1BS0dnYVJzDQpaR0Z3T2k4dkwwTk9QVzFwYkdG
    aUxWZEpUbE5XVWkxRVF5MURRU3hEVGoxQlNVRXNRMDQ5VUhWaWJHbGpKVEl3DQpTMlY1SlRJd1Uy
    VnlkbWxqWlhNc1EwNDlVMlZ5ZG1salpYTXNRMDQ5UTI5dVptbG5kWEpoZEdsdmJpeEVRejF0DQph
    V3hoWWl4RVF6MXNiMk5oYkQ5alFVTmxjblJwWm1sallYUmxQMkpoYzJVL2IySnFaV04wUTJ4aGMz
    TTlZMlZ5DQpkR2xtYVdOaGRHbHZia0YxZEdodmNtbDBlVEFoQmdrckJnRUVBWUkzRkFJRUZCNFNB
    RmNBWlFCaUFGTUFaUUJ5DQpBSFlBWlFCeU1BNEdBMVVkRHdFQi93UUVBd0lGb0RBVEJnTlZIU1VF
    RERBS0JnZ3JCZ0VGQlFjREFUQU5CZ2txDQpoa2lHOXcwQkFRc0ZBQU9DQVFFQWNiNGt4YTFQaFJh
    TVNjWW04ZkxrN09ZWkxraFRqOVNHcm1VTHRkaWNhYjVmDQo3N2FvMUNjcUZjQ3RaL3Q4dlFCSnZv
    MVlHc3podUJJY0RvRjRQMFZnUEdPeW5LUG1ySjQxUkpRWVJNcExEZk93DQp0dlRZaXI5OU9ZdHNx
    NEFocEQ2R2MrVjFWS2ZRMmVpZWFRSVB0QkZ3d05vZXdrcFFsd3ZPWEZDZ0tZYjlqMlJmDQp2MVFL
    VzVXd1cySm9SYURsa1htMERYc0w5dHgyT2VNTHZZMWNwVkFrZjVZRnVKcE5VVzJmTEhXYUMwUWtq
    dkZ1DQpIZXhHSm0raE9kbWFJTFBLUnF1bE45UHVPbjVlZ1U0YzJLUGpUQW50UTJxQUZISmEwS00y
    OXdtU05QdklKbUhzDQpoYnA2L3pxWDJUclEwUUMwYkMyUDBnUGZGOHJHcjhVWGc4NjE5WFFoenc9
    PQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ0K

  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZB
    QVNDQktZd2dnU2lBZ0VBQW9JQkFRQzFnN1RQcmg4K0VueFUKeXF4QTRoMUVTTXp5dTJObWdaR0g2
    aWhQK2ZrRzNOVVNXUFJHd3hTZm9SVERxSnBPNHBsbFNldDVYajF4cUF6TApic3dnT2tmVDR2S1By
    K2xmMEVrWnRUWkdCOVZFQ0E1UzFyK1gzS0xWWjdlUnVMU0NFZnpUSlZHQ3lncDljSlhwCnp6SVgv
    TEhLeVU4WG1VTC9mdWZpVjMxRi9td0dCNzFGRHN1M1ZvRDVLSTVSeWJROG5IeGV2eU9seVpIUjZW
    TkcKN2ZjeDFUeVVFSDhOd0NRWDlmcUNZeHYrUDlaSTgzQ0dFQzBOZnVtSWNrbXMzSWZEa201NHA0
    TytCd28vSkpDRwpyMnVhaGVRbVplcmR4bEw1TjVkTjhUM2V5d1JMRktzTXpRUUFwYjJydk03TVcx
    djFPejgzVk5SbzBlVjlEeklBCnVqc3R1cXNiQWdNQkFBRUNnZ0VBRW5JaitjYjBIZGE3RTlMVTFu
    TWtEa0JuczNNZmt0Y3Y5dVB3M00vR1l0QW0KUndzTEovWERMc1dyMm9aVHlCaDNCamdRMmZDZHhl
    TVNDY3BrckJIQUl1UTVTaWpTU281Y0gyU3U4MGJ3Z1UxZwpSMExUalpjNlpQMTVSakhEQmtUVnNJ
    OW1UU2hERUtSVVY4SmFrTjE1SStaNVJ5aW9DbGJYTWNVNlVkYWRHNitaCjBobXVzWXlBMnRsYyt0
    bC9WekQ4R1Fsa0M0a2tYazlVV0t4cmcyNExFOHMyNVVRZGh0SnowdGhtN2ZONlp4MW8KN0ZnRWxM
    TlRUa3o4VXNxV1dEandXTi8rOU92UWM0Znd5eGVhbENRRWVNckFxZFd3MTFPMTZBVnZlUUVGWEF0
    YwpuZklqYXBZejBZQngyaUJIdlVFcCtzdnNJdFo3WFJvL1cyQys2MTFSNFFLQmdRRGUzVFI2clU2
    NlNCeUdISXI3Cmo0NGFpSitrenhhb29GWEZSRGl5NTdaMzBFUUhFYm9ZSXZ5YUorOTJSM2xCdzVE
    MUV6b1Vkbk9YdFlKM2FrRGwKVUVjYW12T2RDWVVvSEFaTlhveitvSjJ1aXQ4bVQ1amRlUEEwajIr
    ZDdKM2lHL05QODlta1NjTWM4blljMWNGUQpDSGdRTHB6ZFk3eHdjcmsxNHBBYmlxc25ud0tCZ1FE
    UWdLQlNKUjgxUS9OSXhzRXNsSEZ0U2syNzErSWQ4OGRyCjRJdVhvVDBka0Z0Yk5zdXFxL0VnTUNr
    cGkxTVk5UVJpS21IU21yem5xOTlFMExmaHNGeXVETHo2cUdoMkVzNGsKNTRycC9PSGh4OVpiTmlQ
    U3lsM3dxMC83VmZHS1BBU1VGdi90NktPbWJJcjhscnN2aVdjZFdwaWo0d0RzWG9mdgo2S2Qva3pi
    N0JRS0JnQS9Na3JuWHEyc2RUWmhjVWFYL3lVMHNQbFVLc1VxSEEwMld4b1k0VXdFdmJJTXJ5SXVK
    CmYycldSZTJXcDR2MzkwREllaWVWTmlDZEo0Q2JzYm9QOU5wMy9hazJVWkJFWEZZRHkrOEpKK1NG
    eDhnSmdJYkMKMmhSL3pxUGRjRnZsSzF5UnB1NDBwSFphNGZDdFhxVHoxTDhnN3RIckRpTFNuenFv
    c3hxZ3UvMTFBb0dBSWdOSgpvL3pnU1cwclM4ejRpRkF5N0xRNVdCSlFsYmhGNk9nNWZXUFZOM1Jz
    SXNZZWxWbjFQTjMrYVFPTWE3N1VsenI0CnVFVjcyWU1sS2ZHdWZZZXFwczMzS2lDODRiNFJtTjJZ
    d0xEN0hEemdVQUxWOXpZQit4ZkhOV1lBd0I4b1ZBd28KZGVRRWhrcWdwYkhsR1UwZDRDRCtVNFhk
    aWJHbUZWSHJ1UmtIMkEwQ2dZQlVlZ1NJQlhhVTVzeU1FSWU4YkRNZQplS21YSDhFMGdSWWRuRElw
    SGI2TVZSeXdVcmFmVnVremhKOCt1ZFl6eVM2Mm9RYW83VGhUdU9Eb2VEeE9WejV2ClZNRTZKMldy
    MWVKc3MyUzZPYjluMmhSSjNvanU4ZE5ZenVhaEw4Z2VqcmJLZjQ4a01zV0lYOHhMUC9FN2RCLysK
    MmhycExnTnhpZk1XL1dISWhsbEh5dz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K